### ISSUE TITLE
XML Language Server / Preparation is too slow

### ISSUE THREAD

**Issue by eliasbalasis** [eclipse-wildwebdeveloper/wildwebdeveloper#1215]
Continuing form https://github.com/eclipse/lemminx-maven/issues/406

The Language Server preparation cycle is too long, about 7 minutes.
but only when Preferences => XML (Wild Web Developer) => Validation & Resolution => Enable Validation is turned on

This behavior is clearly related to "Wild Web Developer" components.

**Comment by vrubezhny** [comment]
@eliasbalasis could you please enable the `Log to File` in `Language Servers->Logs` for `LemMinX` Language Server, repeat the experiment and then attach the logs here (See the preference page for the hints on locating the language servers log files .

Also, if possible, could you attach the Eclipse log file (usually saved to your workspace `.metadata` directory.

**Comment by eliasbalasis** [comment]
[org.eclipse.wildwebdeveloper.xml.log](https://github.com/eclipse/wildwebdeveloper/files/11522366/org.eclipse.wildwebdeveloper.xml.log)

**Comment by eliasbalasis** [comment]
Off the top of my head:

Maven 3.9.1 as default, under Preferences => Maven Installations

jdk8u362-b09 as default, under Preferences => Java => Installed JREs

JavaSE-1.8 execution environment for the Maven modules of the test case.

I am not using Node.js for this experiment, just Maven and Java

I haven't opened any other files during the experiment, just Maven POM manifests.

**Comment by angelozerr** [comment]
Have you performance problem with XML validation which is not à pom.xml?

For instance you can rename your pom.xml to foo.xml and check if validation performance is quick.

If it is quick it means that there is a problem with lemminx-maven validation

**Comment by eliasbalasis** [comment]
I cannot guess what kind of validation you expect on plain XML files.

However, the behaviors being tested are Maven specific, therefore I am suspecting a relationship to lemminx-maven validation but in relation to Wild Web Developer.

**Comment by vrubezhny** [comment]
For sure the issue can be of two origins - the XML Editor (Lemminx LS) itself on one side as it provides its validation and editing functionality (content assist, hovers etc) and LemMinX-Maven extension (POM Editing) on the other with its Maven project related validation and editing functionality.

LemMinX-Maven initialization and validation for sure takes quite a lot of time as every `pom.xml` from parents to children is to be loaded and built into a maven project with Apache Maven builder before it's cached for further use. For sure it takes time to build the projects cache for the whole workspace. 

But if turning the XML validation off really significantly improves the performance - we have to look at what's happening on in the Lemminx LS side as well.

**Comment by eliasbalasis** [comment]
I confirm (see https://github.com/eclipse/lemminx-maven/issues/406)

> When Preferences => XML (Wild Web Developer) => Validation & Resolution => Enable Validation is turned off
> the Maven POM editor responds almost instantly.

**Comment by mickaelistria** [comment]
I suspect turning off validation can cause the MavenDiagnosticsParticipant from lemminx-maven is not invoked, and thus not triggering nor delaying work. However, this initialization of lemminx-maven will have to happen at some point if you want tools to be efficient. I'm wondering whether the validation is blocking other operations or does it work in background?

**Comment by eliasbalasis** [comment]
It seems the lemminx-maven initialization takes about 7 minutes before tools can be efficient.

Given that the XML language server process terminates when the last Maven POM editor is closed,
we have to wait 7 minutes eery time we open a new editor which is unbearable.

If the above is correct,
I would suggest at least not terminating the XML language server, even though the initialization would still be too long.

**Comment by angelozerr** [comment]
> It seems the lemminx-maven initialization takes about 7 minutes before tools can be efficient.

This initialisation should never done when XML language server is started.

**Comment by angelozerr** [comment]
@vrubezhny I suggest you move this initialization in a thread lile ccompletalefuture and you lsp progress to show to the user the initialization progress. We use lsp progress to load Qute project in https://github.com/redhat-developer/quarkus-ls/blob/7d08dc2c8d2f6cd68f52a6747c5a5afddedfa3fe/qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/project/QuteProjectRegistry.java#L413

**Comment by eliasbalasis** [comment]
In case it helps you.
This is still reproducible with Eclipse 2023-06.

**Comment by eliasbalasis** [comment]
It seems this has been fixed in Eclipse Plugin "org.eclipse.wildwebdeveloper.xml" 1.2.0.202306201632

**Comment by mickaelistria** [comment]
@eliasbalasis thanks!
