### ISSUE TITLE
Feature request: Rename angular component (ts or js)

### ISSUE THREAD

**Issue by rloutrel** [eclipse-wildwebdeveloper/wildwebdeveloper#1277]
I, as an angular developer, wish I could rename an angular component with the "refactor->rename" option, so that I do not have to modify manually all references to the component manually in all files.

![image](https://github.com/eclipse-wildwebdeveloper/wildwebdeveloper/assets/11015691/058b6ade-707d-4c6e-b9c0-3564977fcfcf)

Ubuntu 22.04
Eclipse (installed with the installer): Version: 2023-09 M1 (4.29.0 M1)
Eclipse Web Developer Tools 3.30: Version: 3.30.0.v202305230750

**Comment by vrubezhny** [comment]
@rloutrel Does such a rename support works in VSCode (with `Angular.ng-template` extension installed)?  

The  support for rename an angular component is to be provided by Angular Language Server, so please report this feature request to the Angular Language Service project (https://github.com/angular/vscode-ng-language-service/issues) 

Thank you.

**Comment by rloutrel** [comment]
Could https://github.com/angular/vscode-ng-language-service/issues/815 be the corresponding feature ?

From that comment ( https://github.com/angular/vscode-ng-language-service/issues/815#issuecomment-1008587442 ), I understand, there is an extension as workaround. Is it something which can be imported/used in Eclipse as in or used as inspiration for a similar extension in wwd (I do not have any knowledge about the eclipse architecture)?

**Comment by vrubezhny** [comment]
I believe - yes, according to https://github.com/angular/vscode-ng-language-service/issues/815 description, it could be.

Regarding the [Rename Angular Component](https://marketplace.visualstudio.com/items?itemName=tomwhite007.rename-angular-component) Extension - I cannot answer right here and right now if we can use this in WWD, but it probably is worth to be investigated. 
 
Any contributions are welcomed.
