### ISSUE TITLE
Unsigned commons-compress

### ISSUE THREAD

**Issue by vgcpge** [eclipse-wildwebdeveloper/wildwebdeveloper#1282]
## Prerequisites
A fresh installation of Eclipse Platform 2022-09 (4.25)

## Test steps
Install Node.js embedder from Wild Web Developer from https://download.eclipse.org/wildwebdeveloper/releases/latest/

### Expected result
No warnings about unsigned content.

### Actual result
Unsigned org.apache.commons.commons-compress 1.23.0
<img width="468" alt="Screenshot 2023-07-16 at 13 51 14" src="https://github.com/eclipse-wildwebdeveloper/wildwebdeveloper/assets/129676242/ef0e2fa8-4b1c-4dae-bb1a-46a3a52a5683">

Can't reproduce on Eclipse 2023-09 (4.29)

**Comment by vrubezhny** [comment]
Was this an update  of Embedded Node.js or a fresh installation on both platforms? 

Could you please find and take a look at the logs left after installing Embedded Node.js on  `Eclipse Platform 2022-09 (4.25)`  (look at <your workspace>/.metadata/ *.log files) if any exceptions happened during the installation process?

**Comment by vgcpge** [comment]
This was a fresh installation. No exceptions could happen, as this dialog is shown before actual installation happens.

**Comment by vrubezhny** [comment]
> No exceptions could happen, as this dialog is shown before actual installation happens.

Some exception could happen on signing verification after the jars were downloaded.

**Comment by vgcpge** [comment]
I've just tried to reproduce again.
When installing Eclipse Platform 2022-09 with Eclipse Installer, more warnings about unsigned content appear. So this problem likely originates from Eclipse Platform itself and is unrelated to Wild Web Developer.
<img width="604" alt="Screenshot 2023-07-16 at 16 03 13" src="https://github.com/eclipse-wildwebdeveloper/wildwebdeveloper/assets/129676242/e29ae0c0-f60c-4715-9c38-fa7ed5476612">

**Comment by vrubezhny** [comment]
It could be that some singing/verification functionality has changed between 2022-09 and 2023-09 so the older one cannot correctly verify the latest signed jars. 
Have you tried to install an older WWD Embedded Node.js version...  for instance https://download.eclipse.org/wildwebdeveloper/releases/0.15.0/ (2022-07-29) to a fresh Eclipse Platform 2022-09 ( 4.25) installation ? Does it have the same problem?

**Comment by vgcpge** [comment]
> It could be that some singing/verification functionality has changed between 2022-09 and 2023-09 so the older one cannot correctly verify the latest signed jars. Have you tried to install an older WWD Embedded Node.js version... for instance https://download.eclipse.org/wildwebdeveloper/releases/0.15.0/ (2022-07-29) to a fresh Eclipse Platform 2022-09 ( 4.25) installation ? Does it have the same problem?

I've tried suggested update site and successfully installed  Node.js embedder 0.3.0 in Eclipse 2022-09!

**Comment by vrubezhny** [comment]
So, it looks like old Eclipse Platform cannot verify the jars that are signed with algorithms/keys produced/updated after the  Eclipse Platform 2022-09 (4.25) release date and this either an expected behavior or an issue in Eclipse Platform itself.
Thanks for reporting and helping to triage.
