### ISSUE TITLE
Error Installing SAP ADT (New software)

### ISSUE THREAD

**Issue by ariel3557** [eclipse-wildwebdeveloper/wildwebdeveloper#1286]
HI, 
I'm trying to install SAP ADT (Abap Development Tools) on Eclipse IDE for web and javascript developers found on the appliation store of pop! os (Flatpak) 

I'm getting an error: 
![image](https://github.com/eclipse-wildwebdeveloper/wildwebdeveloper/assets/7221989/d50449c1-e6af-410f-ad5a-fad7b2867c79)

I've been researching  about the error, and found a post in the sap site, that says that we should run Eclipse in ROOT mode ( [POST](https://answers.sap.com/questions/47009/abap-in-eclipse-error-when-installing-new-software.html ) ), but i'm unable to do that with Flatpak when i run it with sudo: _sudo flatpak run org.eclipse.Javascript_
![image](https://github.com/eclipse-wildwebdeveloper/wildwebdeveloper/assets/7221989/3b308cce-84cb-498f-9473-b5d65abb5500)
(the error says in English: It's not installed)

Someone knows how to solve this? 
Thanks

P.S - I apologize in advance for any inconvenience I could be causing, I'm new in the Linux world and Flatpak.

**Comment by vrubezhny** [comment]
Is it possible for you to install SAP ADT on "Eclipse IDE for web and javascript developers"  installed without using Flatpak?  
I mean, Flatpak itself is a cool thing, but is very restricted in access rights for the software to be installed  so not any available software can be be installed and  normally work on Flatpak,. Given this, the first step I would take is to install Eclipse locally (without using Flatpak) and try installing SAP ADT to make sure it really can be installed and executed.

It looks like SAP ADT is not OSS and quite specific in installation and requires to make some additional configurations by a system  administrator, according to https://help.sap.com/docs/SAP_NETWEAVER_740/7bfe8cdcfbb040dcb6702dada8c3e2f0/a3314a7fd9384ce8a40eff2d3b144628.html... Did you followed carefully the recommendations in Configuration Guide referenced there (https://help.sap.com/docs/link-disclaimer?site=http%3A%2F%2Fscn.sap.com%2Fdocs%2FDOC-47656)? 

I'm sorry, I don't have neither a SAP account required to read the Configuration Guide nor to try installing the SAP ADT to triage your issue.

**Comment by ariel3557** [comment]
Thanks for your reply Victor. 
As you suggested, I've installed Eclipse the normal way and not using the Flatpak package. 
I've successfully installed SAP ADT. 

Again, thanks for your assistance.
