### ISSUE TITLE
State for "Verbose output" is not stored in the configurations for "Chrome Debug"

### ISSUE THREAD

**Issue by Si-So** [eclipse-wildwebdeveloper/wildwebdeveloper#1291]
# Steps to reproduce: #
1. Create a new Configuration for "Chrome Debug"
2. Check the checkbox for "Verbose output" in the first tab (Program)
3. Press Apply to store the settings
4. Close the debug configurations menu 
5. Open the debug configuration menu again and navigate to the configuration you just created
6. The verbose checkbox is not checked, even though it should be checked. 

# Environment # 
Eclipse 2023-06

**Comment by vrubezhny** [comment]
Thanks for reporting

**Comment by Si-So** [comment]
Thank you :)
