### ISSUE TITLE
Eclipse JSP formatter is not properly handling the embedded CSS

### ISSUE THREAD

**Issue by bajins** [eclipse-wildwebdeveloper/wildwebdeveloper#1311]
This can cause the CSS to be formatted incorrectly, which can make it difficult to read and understand

Version: 2023-06 (4.28.0)
Build id: 20230608-1333

refer: https://stackoverflow.com/questions/10946133/prevent-eclipse-from-destroying-css-formatting

before formatting：
![1](https://github.com/eclipse-platform/eclipse.platform.ui/assets/30252550/0e7b486f-93b0-4f42-a0e2-5f50c18266a4)

after formatting：
![2](https://github.com/eclipse-platform/eclipse.platform.ui/assets/30252550/c174bf1c-4501-40e3-bdd5-8d85e8a4b0dd)

refer: https://github.com/eclipse-platform/eclipse.platform.ui/issues/1023

**Comment by akurtakov** [comment]
As I said in https://github.com/eclipse-platform/eclipse.platform.ui/issues/1023#issuecomment-1680102095 : 
JSP editor comes from WebTools project. Please report the bug to them https://bugs.eclipse.org/bugs/enter_bug.cgi?product=WTP%20Source%20Editing&Bugzilla_restrictlogin=on&GoAheadAndLogIn=Log%20in 

You can use this project for CSS editing but you would have to extract css into separate file.
