### ISSUE TITLE
consider using vscode-js-debug/dapDebugAdapter for Chrome

### ISSUE THREAD

**Issue by mickaelistria** [eclipse-wildwebdeveloper/wildwebdeveloper#1358]
vscode-js-debug adapter can debug Chrome/Chromium using the `pwa-chrome` launch kind. Wild Web Developer should try to use it, which is already used for plain Node.js launches, instead of the custom Chrome extension.
That would improve consistency inside Wild Web Developer, make it more consistent with VSCode and would allow to remove a bunch of node_modules.

**Comment by mickaelistria** [comment]
WIP at https://github.com/eclipse-wildwebdeveloper/wildwebdeveloper/pull/1359

**Comment by akurtakov** [comment]
WIP seems to have been finished and merged, thus closing this one.
