### ISSUE TITLE
Get rid of RCP/IDE package?

### ISSUE THREAD

**Issue by mickaelistria** [eclipse-wildwebdeveloper/wildwebdeveloper#1444]
Build IDE packages takes a lot of time and resources on each build.
Is there anyone actively using those builds? If not, we should consider removing them.

**Comment by akurtakov** [comment]
These have been the source for https://flathub.org/apps/org.eclipse.Javascript which unfortunately I haven't found the time to update since July. So most likely these are up for removal too.

**Comment by akurtakov** [comment]
This has been fixed via https://github.com/eclipse-wildwebdeveloper/wildwebdeveloper/pull/1493
