### ISSUE TITLE
Need to update version of node due to vulnerabilities

### ISSUE THREAD

**Issue by wnm3** [eclipse-wildwebdeveloper/wildwebdeveloper#1447]
Our scanner is complaining about the version of node installed in eclipse/.node/node-v18.17.1-linux-x64/bin/node stating it needs to be at 18.18.2 or higher. What is the process for us to perform this update? Or is there a newer version of Wild Web Developer that will take care of this for us?

**Comment by wnm3** [comment]
Sorry, on further investigation, there is an updated version to v18.18.2... I just needed to delete the old version.

**Comment by vrubezhny** [comment]
@wnm3 Sorry for the late answer...

Yes, https://download.eclipse.org/wildwebdeveloper/releases/latest/ currently contains v.1.3.3 which embeds Node.js v.18.18.2, So you can update from it.

Also you can try updating from the latest snapshot - https://download.eclipse.org/wildwebdeveloper/snapshots - this currently  will install Node.js v20.11.0
