### ISSUE TITLE
Saving language server settings breaks the POM editor outline handling

### ISSUE THREAD

**Issue by marioja** [eclipse-wildwebdeveloper/wildwebdeveloper#1455]
In eclipse 2023-12, if I go to preferences/languageserver and I disable all language server setting (by unchecking the check box), then the settings saved to the .metadata\.plugin\org.eclipse.core.runtime\.settings\org.eclipse.lsp4e.prefs file will cause the Outline view to display the message "There is no active editor that provides an outline" and does not provide any outline information for the POM file.  This will occur upon restarting eclipse.

I work for a large public organization that requires all language servers to be disabled due to proxy connection restrictions.  As a result, the POM outline which is very important in handling large POM files is not operational at all.

If you remove the lsf4e.prefs file, the outline is back upon restart of eclipse but all language servers are enabled.

I think that the prefix // on each preference line is what is cause the issue.  See the org.eclipse.lsp4e.prefs file after turning off all language server:
```//org.eclipse.wildwebdeveloper.angular/org.eclipse.wildwebdeveloper.html=false
//org.eclipse.wildwebdeveloper.angular/org.eclipse.wildwebdeveloper.ts=false
//org.eclipse.wildwebdeveloper.css/org.eclipse.wildwebdeveloper.css=false
//org.eclipse.wildwebdeveloper.css/org.eclipse.wildwebdeveloper.less=false
//org.eclipse.wildwebdeveloper.css/org.eclipse.wildwebdeveloper.scss=false
//org.eclipse.wildwebdeveloper.eslint/org.eclipse.wildwebdeveloper.js=false
//org.eclipse.wildwebdeveloper.eslint/org.eclipse.wildwebdeveloper.jsx=false
//org.eclipse.wildwebdeveloper.eslint/org.eclipse.wildwebdeveloper.ts=false
//org.eclipse.wildwebdeveloper.eslint/org.eclipse.wildwebdeveloper.tsx=false
//org.eclipse.wildwebdeveloper.html/org.eclipse.wildwebdeveloper.html=false
//org.eclipse.wildwebdeveloper.json/org.eclipse.wildwebdeveloper.json=false
//org.eclipse.wildwebdeveloper.jsts/org.eclipse.wildwebdeveloper.js=false
//org.eclipse.wildwebdeveloper.jsts/org.eclipse.wildwebdeveloper.jsx=false
//org.eclipse.wildwebdeveloper.jsts/org.eclipse.wildwebdeveloper.ts=false
//org.eclipse.wildwebdeveloper.jsts/org.eclipse.wildwebdeveloper.tsx=false
//org.eclipse.wildwebdeveloper.vue.syntax/org.eclipse.wildwebdeveloper.vue=false
//org.eclipse.wildwebdeveloper.vue/org.eclipse.wildwebdeveloper.vue=false
//org.eclipse.wildwebdeveloper.xml/org.eclipse.core.runtime.xml=false
//org.eclipse.wildwebdeveloper.xml/org.eclipse.wildwebdeveloper.dtd=false
//org.eclipse.wildwebdeveloper.xml/org.eclipse.wildwebdeveloper.rng=false
//org.eclipse.wildwebdeveloper.xml/org.eclipse.wildwebdeveloper.xsd=false
//org.eclipse.wildwebdeveloper.xml/org.eclipse.wildwebdeveloper.xsl=false
//org.eclipse.wildwebdeveloper.yaml/org.eclipse.wildwebdeveloper.yaml=false
eclipse.preferences.version=1
```

**Comment by AObuchow** [comment]
The POM/Maven editor in Eclipse is now provided by the XML language server in conjunction with LemMinX-Maven (this has been the case for a while now). Disabling the XML language server is likely the reason you are getting the "There is no active editor that provides an outline" error.

I'm not sure if there's any workaround to get the POM editor outline view while having all language servers disabled.

**Comment by mickaelistria** [comment]
@AObuchow is right. Wild Web Developer or m2e don't support the case of "disabled language servers" for edition.
The only path forward for your case is to make the necessary language servr work decently with the proxy restrictions (ie either forward some proxy settings, or enable some kind of "offline" mode).
