### ISSUE TITLE
getting server error

### ISSUE THREAD

**Issue by yogesh4701** [eclipse-wildwebdeveloper/wildwebdeveloper#1588]
i could not proced after : 
the error is:
Type Exception Report  Message Error instantiating servlet class [org.springframeork.web.servlet.DispatcherServlet]  Description The server encountered an unexpected condition that prevented it from fulfilling the request.  Exception  javax.servlet.ServletException: Error instantiating servlet class [org.springframeork.eb.servlet.DispatcherServlet] 	org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:481) 	org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93) 	org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:660) 	org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:346) 	org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:388) 	org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63) 	org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:928) 	org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1791) 	org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52) 	org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1190) 	org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) 	org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63) 	java.base/java.lang.Thread.run(Thread.java:1570) Root Cause  java.lang.ClassNotFoundException: org.springframeork.eb.servlet.DispatcherServlet 	org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1308) 	org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1120) 	org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:481) 	org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93) 	org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:660) 	org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:346) 	org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:388) 	org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63) 	org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:928) 	org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1791) 	org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52) 	org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1190) 	org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) 	org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63) 	java.base/java.lang.Thread.run(Thread.java:1570) Note The full stack trace of the root cause is available in the server logs.

**Comment by mickaelistria** [comment]
This issue doesn't seem related to Wild Web Developer. If it is, please reopen with either steps to reproduce that involve Wild Web Developer, and/or a stacktrace showing some Eclipse-releted methods.
