### ISSUE TITLE
npm ERR! "SELF_SIGNED_CERT_IN_CHAIN"

### ISSUE THREAD

**Issue by TICPetrobras** [eclipse-wildwebdeveloper/wildwebdeveloper#1685]
Prezados, sou do Atendimento TIC 881 Petrobras, tenho o Node.js v20.13.1 instalado no meu notebook com imagem Petrobras, estou utilizando o meu wifi particular e conectado na VPN Petrobras através do Cisco Anyconnect. Ao tentar instalar o Yarn, através do comando npm install ---global yarn apresentou o seguinte erro e log. "SELF_SIGNED_CERT_IN_CHAIN"

<img width="670" alt="SELF_SIGNED_CERT_IN_CHAIN" src="https://github.com/user-attachments/assets/342de12c-1de6-4788-b865-cee0addbe32b">
[2024-09-30T19_41_02_185Z-debug-0.log](https://github.com/user-attachments/files/17195914/2024-09-30T19_41_02_185Z-debug-0.log)

**Comment by TICPetrobras** [comment]
LOG:

0 verbose cli C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js
1 info using npm@10.5.2
2 info using node@v20.13.1
3 timing npm:load:whichnode Completed in 2ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:C:\Program Files\nodejs\node_modules\npm\npmrc Completed in 3ms
6 timing config:load:builtin Completed in 3ms
7 timing config:load:cli Completed in 1ms
8 timing config:load:env Completed in 1ms
9 timing config:load:project Completed in 2ms
10 timing config:load:file:C:\Users\AEEQ0M\.npmrc Completed in 1ms
11 timing config:load:user Completed in 1ms
12 timing config:load:file:C:\Users\AEEQ0M\AppData\Roaming\npm\etc\npmrc Completed in 0ms
13 timing config:load:global Completed in 0ms
14 timing config:load:setEnvs Completed in 0ms
15 timing config:load Completed in 10ms
16 timing npm:load:configload Completed in 10ms
17 timing config:load:flatten Completed in 3ms
18 timing npm:load:mkdirpcache Completed in 1ms
19 timing npm:load:mkdirplogs Completed in 0ms
20 verbose title npm install yarn
21 verbose argv "install" "---global" "yarn"
22 timing npm:load:setTitle Completed in 1ms
23 timing npm:load:display Completed in 1ms
24 verbose logfile logs-max:10 dir:C:\Users\AEEQ0M\AppData\Local\npm-cache\_logs\2024-09-30T19_41_02_185Z-
25 verbose logfile C:\Users\AEEQ0M\AppData\Local\npm-cache\_logs\2024-09-30T19_41_02_185Z-debug-0.log
26 timing npm:load:logFile Completed in 3ms
27 timing npm:load:timers Completed in 0ms
28 timing npm:load:configScope Completed in 0ms
29 timing npm:load Completed in 44ms
30 timing config:load:flatten Completed in 1ms
31 timing arborist:ctor Completed in 0ms
32 silly logfile done cleaning log files
33 timing idealTree:init Completed in 4ms
34 timing idealTree:userRequests Completed in 2ms
35 silly idealTree buildDeps
36 silly fetch manifest yarn@*
37 silly placeDep ROOT yarn@ OK for:  want: *
38 timing idealTree:#root Completed in 70176ms
39 timing idealTree:node_modules/yarn Completed in 0ms
40 timing idealTree:buildDeps Completed in 70177ms
41 timing idealTree:fixDepFlags Completed in 0ms
42 timing idealTree Completed in 70184ms
43 timing command:install Completed in 70190ms
44 verbose type system
45 verbose stack FetchError: request to https://registry.npmjs.org/yarn failed, reason: self-signed certificate in certificate chain
45 verbose stack     at ClientRequest.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\minipass-fetch\lib\index.js:130:14)
45 verbose stack     at ClientRequest.emit (node:events:519:28)
45 verbose stack     at _destroy (node:_http_client:880:13)
45 verbose stack     at onSocketNT (node:_http_client:900:5)
45 verbose stack     at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
46 verbose cwd C:\Windows\System32
47 verbose Windows_NT 10.0.22631
48 verbose node v20.13.1
49 verbose npm  v10.5.2
50 error code SELF_SIGNED_CERT_IN_CHAIN
51 error errno SELF_SIGNED_CERT_IN_CHAIN
52 error request to https://registry.npmjs.org/yarn failed, reason: self-signed certificate in certificate chain
53 verbose exit 1
54 timing npm Completed in 71562ms
55 verbose unfinished npm timer reify 1727725263557
56 verbose unfinished npm timer reify:loadTrees 1727725263559
57 verbose code 1
58 error A complete log of this run can be found in: C:\Users\AEEQ0M\AppData\Local\npm-cache\_logs\2024-09-30T19_41_02_185Z-debug-0.log

**Comment by mickaelistria** [comment]
Can you please post in english?
How is this issue related to Wild web developer?

**Comment by mickaelistria** [comment]
How does it relate to Wild Web Developer? Does this issue only happen when using it in the Eclipse IDE?

**Comment by mickaelistria** [comment]
I'm closing it here, it looks like your error is with plain NPM CLI. Please get in touch with NPM support channels.
