### ISSUE TITLE
Update to new lemminx version

### ISSUE THREAD

**Issue by laeubi** [eclipse-wildwebdeveloper/wildwebdeveloper#1714]
I'm currently a bit blocked by
- https://github.com/eclipse-lemminx/lemminx/issues/1694

so I'd like to ask for the update here already even though there is sadly not yet a release schedule.

**Comment by rgrunber** [comment]
Sounds fine to me.

**Comment by laeubi** [comment]
According to

- https://github.com/eclipse-lemminx/lemminx/pull/1708#issuecomment-2498482295

there is a new lemminx release now :+1:

**Comment by laeubi** [comment]
According to this PR it is even already updated:
- https://github.com/eclipse-wildwebdeveloper/wildwebdeveloper/pull/1740

if this assumption is correct, I think this can be closed now.
