### ISSUE TITLE
README link to standalone Wild Web Developer IDEs is broken

### ISSUE THREAD

**Issue by DynamicProdBreaker** [eclipse-wildwebdeveloper/wildwebdeveloper#1747]
The README states:

> Get an Eclipse IDE for JavaScript and Web developers: download from https://download.eclipse.org/wildwebdeveloper/releases/latest/IDEs , unpack and run.

However the latest version that has the "IDEs" section is Eclipse Wild Web Developer 1.3.3

Did Eclipse maintainers forget to publish the standalone Wild Web Developer IDE packages after version 1.3.3, or did development change and remove the standalone IDEs with the intention of only having the plugin available post 1.3.3, making the README no longer accurate?

**Comment by akurtakov** [comment]
Sorry about that, building the zips/tarballs slowed down the build significantly, wasn't used a lot (less than 100 downloads for each, some of them single digit even), and with addition of new archs support (windows/arm, linux/riscv5....) started to proliferate the download options too much thus they have been dropped. But I forgot to update the documentation, thanks for the reminder!
