### ISSUE TITLE
Replace node debug adapters with vscode-js-debug adapter

### ISSUE THREAD

**Issue by mickaelistria** [eclipse-wildwebdeveloper/wildwebdeveloper#555]
the former vscode-node-debug adapter is now replaced by vscode-js-debug. Wild Web Developer should try to adopt this newer debugger for node/js debugging.

**Comment by akurtakov** [comment]
It seems to even be in npmjs https://www.npmjs.com/package/vscode-js-debug-browsers

**Comment by mickaelistria** [comment]
@vrubezhny maybe something to investigate as you're doing the version bump. If you're lucky, it may actually fix a few conflicts and resolve some issues; otherwise, it can make things worse;)

**Comment by mickaelistria** [comment]
I do not see this package on npm.js, so we'd need to "fetch" it from VSCode like we do for some other packages. I see https://github.com/microsoft/vscode-js-debug/blob/master/src/debugServerMain.ts as entry point in the source but don't see where it is in "binary".

**Comment by akurtakov** [comment]
wouldn't https://github.com/microsoft/vscode-js-debug/archive/v1.54.1.tar.gz be better than fetching from vscode?

**Comment by mickaelistria** [comment]
This is a source tarball (.ts file), not a binary (.js) distribution, it would require to run the build steps.

**Comment by mickaelistria** [comment]
I opened https://github.com/microsoft/vscode-js-debug/issues/926 to ask how this debug adapter can be consumed out of VSCode.

**Comment by mickaelistria** [comment]
I'm experimenting.
This requires a local build (`npm install && npm run compile`) of vscode-js-debug as the only binary distribution doesn't have standalone entry points. I'm currently using `vscode-js-debug/out/src/flatSessionLauncher.js` as entry-point. The launch params need to be augmented on client/IDE side with `param.put("type", "pwa-node");` or `param.put("type", "pwa-chrome") and so on.
I currently see good data going in both directions. However, the application under debugging doesn't seem to be running: nothing is printed in console, no thread is shown.

**Comment by mickaelistria** [comment]
Follow up at https://github.com/microsoft/vscode-js-debug/issues/969

**Comment by mickaelistria** [comment]
Note that recently @vrubezhny managed to reduce the important of this issue by fetching the node-debug2 adapter from https://marketplace.visualstudio.com/items?itemName=ms-vscode.node-debug2 instead of taking it from older VSCode. This has allowed to move to newer VSCode version and at the same time to keep integrating node-debug2.

**Comment by mickaelistria** [comment]
There was some progress on DAP spec that would now allow that.
Wild Web Developer now requires that https://github.com/eclipse/lsp4j/issues/662 and https://github.com/microsoft/vscode-js-debug/issues/1388 are resolved and released before being about to adopt this.

**Comment by mickaelistria** [comment]
And some more: https://github.com/microsoft/vscode-js-debug/issues/926#issuecomment-1741635736
