### ISSUE TITLE
add Vue.js support?

### ISSUE THREAD

**Issue by mickaelistria** [eclipse-wildwebdeveloper/wildwebdeveloper#83]
It seems like there is a language server for Vue.js. Should we add it to Wild Web Developer? Is it good enough? Is Vue.js popular and sustainable enough to be worth it?...

**Comment by mickaelistria** [comment]
cc @jabby

**Comment by jabby** [comment]
I will take this one. 
The vue-language-server sources are are here https://github.com/vuejs/vetur/tree/master/server

**Comment by jabby** [comment]
Not yet. I would like to provide a basic configuration to vue-language server in order to provide some good completion. Actually, the default behaviour is not really good. 
I think I will have some time to spend on it in the beginning of december.

**Comment by jabby** [comment]
@mickaelistria is that a problem if we have a dependency to gson? I think I will parse a JSON file with default configuration and send the conf to vue-language-server

**Comment by mickaelistria** [comment]
Not so much. Wild Web Developer already transitively requires GSon which is used by LSP4J. We'd just need a CQ to officialize that we consume it directly though.
Why do you need to parse a default configuration? Is the file pre-existing in Vue.js? If not, couldn't it be just hardcoded in the LS connection provider? Is there strong need for modifying this file at the moment?

**Comment by angelozerr** [comment]
@jabby GSON is used by LSP4j and it is embed in Eclipse IDE.  So I think it will not a problem. After you can use Map like I have doen to intialize JSON Language Server https://github.com/eclipse/wildwebdeveloper/blob/master/org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/json/JSonLanguageServer.java#L70 (uggly code)

I assume you will need some preferences page. I'm interested by this topic because I would like to contribute with XML Language Server lsp4xml which requires preferences too (where we must set the preferences page, formattings preferences page should perhaps exists in lsp4e, but how to add new formatting options, etc?).

**Comment by mickaelistria** [comment]
There will be no preference page in LSP4E for options or preferences until those are defined in the LSP specification.

**Comment by angelozerr** [comment]
I mean `tabSize` and `insertSpaces` which is part in specification https://microsoft.github.io/language-server-protocol/specification#textDocument_formatting

**Comment by mickaelistria** [comment]
Ok, those can be in the preference page, and be specified from the
extension point also.
I guess we could have a "formatting" page which would list the various LS
and the default (could be IDE defaults if not set) values which could then
be edited by end-user. We need to make sure the PreferenceNode we use are
easy enough to bind listeners so specific integration plugin could
manipulate those properties or listen to them changing from different
preference pages.

**Comment by mickaelistria** [comment]
@jabby Can we have a 1st version that just hardcodes the preferences and later we'll see which ones require to be exposed as dedicated preferences?
Also, have you worked with upstream LS to suggest that the default configuration should be good enough to go without further engineering from adopters? That can be a key factor of success if they want their LS to spread wider and faster.

**Comment by jabby** [comment]
I will try to add next week. Not sure because I will move from my home to new one in few weeks and I need to pack all my things.

**Comment by paulvi** [comment]
just 👍 here.

And hoping @jabby moving went with dominantly good feelings.

**Comment by davydnorris** [comment]
Hi all,

Has there been any further progress in getting the licensing issues sorted out for this? Would really love Vue support in Eclipse!

**Comment by jabby** [comment]
Unfortunately there is no progress. Please add a comment to this issue https://github.com/vuejs/vetur/issues/1458

**Comment by sbernard31** [comment]
Hi all,  still no update on this ?

**Comment by mickaelistria** [comment]
At the moment, this IP issues seems not likely to be resolved. Anyone willing to use vetur in an Eclipse IDE plugin should consider building a separate plugin and publishing it as a separate entry on Eclipse Marketplace.

**Comment by sbernard31** [comment]
Thx for the prompt answer. :pray: 
Too bad this issue still blocked just for IP issue :disappointed:.

Regarding : 
- https://www.gnu.org/licenses/license-list.html#EPL2
- https://www.fsf.org/blogs/licensing/using-the-gpl-for-eclipse-plug-ins

There is maybe some solution but stylint project seems to be not so active : https://github.com/vuejs/vetur/issues/1458#issuecomment-778273657

**Comment by yennor** [comment]
if anybody would know how to do a PR request, they would welcome it
https://github.com/vuejs/vetur/issues/1458

(Unfortunately it would take me forever :-( )

**Comment by davydnorris** [comment]
All,

Has there been any progress at all in getting this resolved?

**Comment by mickaelistria** [comment]
No.

**Comment by kashyap1113** [comment]
Is there any estimated time for this to get sorted and have vue js support in eclipse wild web developer?

**Comment by akurtakov** [comment]
Right now I'm not aware of anyone working to add support for it so it won't be available until someone dedicates time to work on it.

**Comment by mickaelistria** [comment]
@kashyap1113 to be clear, the project is waiting for an interested contributor to take care of contributing it. Would you be interested?

**Comment by kashyap1113** [comment]
@mickaelistria I would love to contribute if I get the opportunity. The thing is, I have used Eclipse but never worked on its development. I would need someone's guidance from time to time as I am completely new to Eclipse development and language servers. I did some research about language server and have understood the concept of it. From @jabby 's comment I have understood that we have to take reference of [Vetur](https://github.com/vuejs/vetur/tree/master/server) which is build in typescript but same way we have to implement it in java and fit it into Eclipse.

I can find reference of integration of other language server at:
[LSP Integrations](https://github.com/eclipse/wildwebdeveloper/tree/master/org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper)

Could you please share any resources which help me better understand or any topics which I must understand before starting this? Especially related to Eclipse development?

**Comment by sebthom** [comment]
To get at least syntax highlighting for *.vue files, you can use my plugin https://github.com/sebthom/extra-syntax-highlighting-eclipse-plugin

**Comment by mickaelistria** [comment]
It was suggested to try Volar Language Server ( @volar/vue-language-server npm package). To try it in Wild Web Developer:
1. add it to `org.eclipse.wildwebdeveloper/package.json`
2. in `org.eclipse.wildwebdeveloper/plugin.xml`, define a content-type for vue files, and create a language server definition for Volar and bind the new langauge server with the new content-type
3. Implement in the language server definition what needs to be done to start the language server and also how to connect the streams.

That should be all!

@sebthom if you're willing to contribute some support for vue.js in Wild Web Developer, that would be welcome.

**Comment by sebthom** [comment]
I am not (yet?) using vue.js myself. Once I do, I may contribute something. No promises made however.

**Comment by zulus** [comment]
Working on latest snapshot :D Please tests, so I'll be able to provide potential fixes

**Comment by vrubezhny** [comment]
@zulus Thanks for the contribution!

Closing the issue as fixed with #1241 .
